stages:
  - clean
  - build-ca
  - build-control
  - config-control
  - deploy-edges
  - waitfor-edges
  - test

image: jasonking/ansible-viptela

variables:
  ANSIBLE_GATHERING: "smart"
  ANSIBLE_CONFIG: "./ansible.cfg"
  ANSIBLE_ROLES_PATH: "./roles"
  GIT_SUBMODULE_STRATEGY: "recursive"

cache:
  paths:
    - myCA/

clean:
  stage: clean
  script:
  - ansible-playbook clean-virl.yml

build-ca:
  stage: build-ca
  script:
  - ansible-playbook build-ca.yml

build-control:
  stage: build-control
  script:
  - ansible-playbook build-virl.yml

config-control:
  stage: config-control
  script:
  - ansible-playbook config-virl.yml

deploy-edges:
  stage: deploy-edges
  script:
  - ansible-playbook deploy-virl.yml

waitfor-edges:
  stage: waitfor-edges
  script:
  - ansible-playbook waitfor-sync.yml
  
test:
  stage: test
  script:
  - ansible-playbook check-sdwan.yml
